version: '3.6'
name: compiler-api
services:
  server:
    container_name: compiler-api
    build: .
    restart: always
    ports:
      - "9000:9000"
    working_dir: /app
    command: [ "./run.sh", "yarn", "dev" ]
    volumes:
      - ../compiler-api/src:/app/src
    environment:
      NODE_ENV: development
